#!/usr/bin/env python3
# Copyright 2026 perspective_grasp
# SPDX-License-Identifier: Apache-2.0

"""
Reads calibration result YAML and generates a ROS 2 launch file
with static_transform_publisher nodes for each calibrated camera.

Usage:
    ./generate_static_tf_launch.py <results_yaml> [output_launch_file]
"""

import sys
from pathlib import Path

import cv2
import numpy as np
from scipy.spatial.transform import Rotation


def load_results(yaml_path: str) -> list[dict]:
    """Load calibration results from OpenCV YAML file."""
    fs = cv2.FileStorage(yaml_path, cv2.FileStorage_READ)
    num_cameras = int(fs.getNode("num_cameras").real())
    results_node = fs.getNode("results")

    results = []
    for i in range(results_node.size()):
        node = results_node.at(i)
        cam_id = int(node.getNode("camera_id").real())
        success = bool(int(node.getNode("success").real()))

        if not success:
            continue

        t_node = node.getNode("T_cam_base")
        rot_vals = []
        rot_node = t_node.getNode("rotation")
        for j in range(rot_node.size()):
            rot_vals.append(rot_node.at(j).real())
        rot_mat = np.array(rot_vals).reshape(3, 3)

        trans_vals = []
        trans_node = t_node.getNode("translation")
        for j in range(trans_node.size()):
            trans_vals.append(trans_node.at(j).real())

        quat = Rotation.from_matrix(rot_mat).as_quat()  # [x, y, z, w]

        results.append({
            "camera_id": cam_id,
            "translation": trans_vals,
            "quaternion": quat.tolist(),
        })

    fs.release()
    return results


def generate_launch_file(results: list[dict], output_path: str):
    """Generate a ROS 2 Python launch file with static TF publishers."""
    lines = [
        "# Auto-generated by generate_static_tf_launch.py",
        "# Do not edit manually - re-run calibration to update.",
        "",
        "from launch import LaunchDescription",
        "from launch_ros.actions import Node",
        "",
        "",
        "def generate_launch_description():",
        "    nodes = []",
        "",
    ]

    for r in results:
        cam_id = r["camera_id"]
        tx, ty, tz = r["translation"]
        qx, qy, qz, qw = r["quaternion"]

        lines.append(f"    # Camera {cam_id}")
        lines.append(f"    nodes.append(Node(")
        lines.append(f"        package='tf2_ros',")
        lines.append(f"        executable='static_transform_publisher',")
        lines.append(f"        name='cam{cam_id}_static_tf',")
        lines.append(f"        arguments=[")
        lines.append(f"            '--x', '{tx:.6f}',")
        lines.append(f"            '--y', '{ty:.6f}',")
        lines.append(f"            '--z', '{tz:.6f}',")
        lines.append(f"            '--qx', '{qx:.6f}',")
        lines.append(f"            '--qy', '{qy:.6f}',")
        lines.append(f"            '--qz', '{qz:.6f}',")
        lines.append(f"            '--qw', '{qw:.6f}',")
        lines.append(f"            '--frame-id', 'base_link',")
        lines.append(f"            '--child-frame-id', 'cam{cam_id}_link',")
        lines.append(f"        ],")
        lines.append(f"    ))")
        lines.append("")

    lines.append("    return LaunchDescription(nodes)")
    lines.append("")

    with open(output_path, "w") as f:
        f.write("\n".join(lines))

    print(f"Generated launch file: {output_path}")


def main():
    if len(sys.argv) < 2:
        print("Usage: generate_static_tf_launch.py <results_yaml> [output]")
        sys.exit(1)

    results_yaml = sys.argv[1]
    output_path = (
        sys.argv[2]
        if len(sys.argv) > 2
        else str(Path(results_yaml).parent / "static_tf_calibrated.launch.py")
    )

    results = load_results(results_yaml)
    if not results:
        print("No successful calibration results found.")
        sys.exit(1)

    generate_launch_file(results, output_path)
    print(f"Generated static TF launch for {len(results)} cameras.")


if __name__ == "__main__":
    main()
